### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by staxfur** [MCWertGaming/caddy-trusted#1]
TODO:

- [ ] add proper readme
- [ ] implement custom root certificate trust
- [ ] add sample site
- [ ] add support for custom docker registry
- [ ] move to minimal image for builder
- [ ] add proper command argument in docker file
- [ ] test running as user in different use cases
- [ ] add unit testing
- [ ] add regular building to docker hub / quay
- [ ] remove old dockerfile
